version: '3'

services:
  app:
    build: .
    image: fffaraz/caddy-logger:latest
    restart: always
    network_mode: host
    command: -a 8080 -d /srv/db-timestamp.sqlite -p 5000
    volumes:
      - ./volumes:/srv
