version: '3'

services:
  app:
    image: fffaraz/caddy-logger:latest
    build: .
    restart: always
    network_mode: host
    command: -d /opt/logger/db.sqlite -p 5000
    volumes:
      - ./volumes/logger:/opt/logger
